---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    name: mongodb
    tier: db
spec:
  containers:
  - image: preetam6126/mongodb:v1
    imagePullPolicy: Always
    name: mongodb
    ports:
      - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    name: mongodb
    tier: db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

      