---
apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    name: mongodb
    tier: db
spec:
  containers:
  - image: preetam6126/mongodb:v1
    imagePullPolicy: Always
    name: mongodb
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  type: LoadBalancer
  selector:
    name: mongodb
    tier: db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  
  

      