apiVersion: v1
kind: Pod
metadata:
  name: catalogue
  labels:
    name: catalogue
    tier: app
spec:
  containers:
  - name: catalogue 
    imagePullPolicy: Always
    image: preetam6126/catalogue:k8
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "100m"

  
  

      