---
apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    name: web
    tier: frontend
spec:
  containers:
  - image: preetam6126/web:k8
    imagePullPolicy: Always
    name: web
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webservie
spec:
  type: LoadBalancer
  selector:
    name: web
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  
  

      