---
apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    name: web
    tier: frontend
spec:
  containers:
  - image: preetam6126/web:k81
    imagePullPolicy: Always
    name: web
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webservice
spec:
  type: LoadBalancer
  selector:
    name: web
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  
  

      